[Variables]
MN=500
TT=   DV=ok, this is epic    PIC=Doge.png
FP=C:\Users\Gabriel\Documents\Rainmeter\Skins\Meme Maker MagickMeter\Doge.png
EF=| Ignore
CCLT=(#MN#)
;__________________________________________________________________________widescreen__________________________________________________________________________
MNW=700
MNH=500
MNC=((#MNW#+#MNH#)/2)
BTT=oh god oh fuck
BDV=donald trump
BFP=C:\Users\Gabriel\Documents\Rainmeter\Skins\Meme Maker MagickMeter\\widescreen\Doge.jpg
BCCLT=(#MNC#+(#MNC#)/2)
;Equalize
